name: Pre-merge RockyLinux

on:
  workflow_dispatch:
    inputs:
      trivy_scan:
        description: 'Run a trivy security scan?'
        default: false
        required: false
        type: boolean
  pull_request:
    paths:
      - scripts/cnode-helper-scripts/guild-deploy.sh
      - scripts/cnode-helper-scripts/cabal-build-all.sh
      - files/tests/pre-merge/rockylinux-guild-deploy.sh.containerfile
      - files/tests/pre-merge/rockylinux-guild-deploy.sh-l.containerfile

jobs:
  guild-deploy-and-build-rockylinux:
    runs-on: ubuntu-latest
    if: github.event.pull_request.draft == false
    steps:
    - name: Provide additional free space
      run: |
        # Workaround to provide additional free space for builds.
        #   https://github.com/actions/virtual-environments/issues/2840
        sudo apt-get remove -y '^dotnet-.*'
        sudo apt-get remove -y 'php.*'
        sudo apt-get remove -y azure-cli google-cloud-sdk google-chrome-stable firefox powershell mono-devel
        sudo apt-get autoremove -y
        sudo apt-get clean
        sudo rm -rf "/usr/share/dotnet"
        sudo rm -rf "/usr/local/lib/android"
        sudo rm -rf "/opt/ghc"
        sudo rm -rf "/usr/local/share/boost"
        sudo rm -rf "$AGENT_TOOLSDIRECTORY"
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - uses: actions/checkout@v2
    - name: Examine head ref
      run: |
        echo "The value of head ref is: ${GITHUB_HEAD_REF}"
    - name: Extract branch from PR (set-output)
      shell: bash
      run: |
        echo "BRANCH=${GITHUB_HEAD_REF}" >> $GITHUB_OUTPUT
        echo "branch=${GITHUB_HEAD_REF}" >> $GITHUB_OUTPUT
        echo "OWNER=${GITHUB_REPOSITORY_OWNER}" >> $GITHUB_OUTPUT
        echo "owner=${GITHUB_REPOSITORY_OWNER}" >> $GITHUB_OUTPUT
      id: pr_branch
    - name: Testing guild-deploy.sh (IO fork of libsodium)
      run: |
        export BRANCH=${{ steps.pr_branch.outputs.branch }}
        export G_ACCOUNT=${{ steps.pr_branch.outputs.owner }}
        export COMMIT=$(git rev-parse --short "$GITHUB_SHA")
        docker build . --file files/tests/pre-merge/rockylinux-guild-deploy.sh-l.containerfile --compress --build-arg BRANCH --build-arg COMMIT --build-arg G_ACCOUNT --tag ghcr.io/cardano-community/pre-merge-rockylinux:guild-deploy-l_${COMMIT}
    - name: Push pre-merge-rockylinux:guild-deploy-l_${COMMIT}
      run: |
        export COMMIT=$(git rev-parse --short "$GITHUB_SHA")
        docker push ghcr.io/cardano-community/pre-merge-rockylinux:guild-deploy-l_${COMMIT}
    - name: Testing cabal-build-all.sh (IO fork of libsodium)
      run: |
        export BRANCH=${{ steps.pr_branch.outputs.branch }}
        export G_ACCOUNT=${{ steps.pr_branch.outputs.owner }}
        export COMMIT=$(git rev-parse --short "$GITHUB_SHA")
        echo "Working from PR Branch ${G_ACCOUNT}/guild-operators/${BRANCH} on Commit ${COMMIT}"
        docker build . --file files/tests/pre-merge/rockylinux-cabal-l.containerfile --compress --build-arg BRANCH --build-arg COMMIT --tag ghcr.io/cardano-community/pre-merge-rockylinux:cabal-l_${COMMIT}
    - if: ${{ inputs.trivy_scan }}
      name: Run Trivy vulnerability scanner
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: 'ghcr.io/cardano-community/pre-merge-rockylinux:cabal-l_${COMMIT}'
        format: 'table'
        exit-code: '0'
        ignore-unfixed: true
        vuln-type: 'os,library'
        severity: 'CRITICAL,HIGH'
